### ISSUE TITLE
Faliure on first setup build

### ISSUE THREAD

**Issue by ghost** [Supercip971/WingOS#17]
Cannot do first build preparation:

![Fail](https://user-images.githubusercontent.com/79633074/129382008-89b42ea4-1243-449d-9c20-ecc24b050538.png)

**Comment by Supercip971** [comment]
You are trying to build it on windows ?

**Comment by Solomon-Wood** [comment]
Yes with WSL

**Comment by kritzikratzi** [comment]
the `unexpected token .... \r' makes me wonder... is it possible you checked out the line endings windows style?
